---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes

- name: start nginx
  service:
      name: nginx
      state: started
  become: yes

- name: Nginx | Links nginx.conf file | file
  become: yes
  file:
    src: "{{ dotfiles_home }}/roles/nginx/files/nginx.conf.link"
    dest: "/etc/nginx/sites-enabled/nginx.conf"
    state: link
    force: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
