---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: Nginx | Links nginx.conf file | file
      file:
        src: "{{ dotfiles_home }}/roles/nginx/files/nginx.conf.link"
        dest: "/etc/nginx/sites-enabled/nginx.conf"
        state: link
        force: yes

