---
- name: download ranger git repo
  git:
    repo: "{{ ranger.repo }}"
    dest: "{{ ranger.download_directory }}"
    version: "{{ ranger.branch }}"

- name: install build packages
  become: true
  package:
    name:
      - make
      - git
      - vim
    state: present

- name: Run 'install' target as root
  become: yes
  make:
    chdir: "{{ ranger.download_directory }}"
    target: install
  when: ansible_python_version[:1] == '3'

- name: install python3
  become: true
  package:
    name: python3
    state: present
  register: install_python3
  ignore_errors: yes

- name: install ranger with python3
  become: yes
  command: python3 setup.py install --optimize=1
  args:
    chdir: "{{ ranger.download_directory }}"
    creates: '/usr/local/bin/ranger'
  when: not install_python3.failed

- name: install ranger with legacy-python
  become: yes
  command: python setup.py install --optimize=1
  args:
    chdir: "{{ ranger.download_directory }}"
    creates: '/usr/local/bin/ranger'
  when: install_python3.failed
