---
###############################################################################
# FZF installation

- name: FZF | Installs FZF | apt
  become: yes
  become_user: root
  apt:
    name: fzf
    state: present

- name: FZF | Installs fd-find | apt
  become: yes
  become_user: root
  apt:
    name: fd-find
    state: present
