---
###############################################################################
# Base system

- name: Base | Updates repositories | apt_repository
  become: yes
  become_user: root
  loop: "{{ base_repositories }}"
  apt_repository:
    repo: "{{ item }}"
    state: present

- name: Base | Installs packages | apt
  become: yes
  become_user: root
  loop: "{{ base_packages }}"
  apt:
    name: "{{ item }}"
    state: present

- name: Base | Cleans packages | apt
  become: yes
  become_user: root
  apt:
    autoremove: yes
