name: Ansible check ubuntu:disco

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with ubuntu:disco
      uses: roles-ansible/check-ansible-ubuntu-disco-action@master
      with:
        targets: "./"
